# AWS Lambda Python base image
FROM amazon/aws-lambda-python:3.11

# Upgrade pip
RUN pip install --upgrade pip

# Copy requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Command to run Lambda handler
CMD ["lambda_handler.handler"]